---
# This is used to run the test suite within CI without requiring extra services.
#
## Usage:
#
# docker-compose -f docker-compose.ci.yml build test
# docker-compose -f docker-compose.ci.yml run --rm test
version: '3'

x-ci-app: &ci-app
  build:
    context: .
    dockerfile: Dockerfile
    target: development
  environment:
    DATABASE_URL: postgres://postgres:postgres@postgres:5432/
    RAILS_ENV: test
    RACK_ENV: test
    BUNDLE_PATH: /usr/src/app/vendor/bundle
  entrypoint: ./bin/docker/entrypoints/wait-for-postgres.sh
  volumes:
    - .:/usr/src/app:cached
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: on-failure
    logging:
      driver: none

  test:
    <<: *ci-app
    command: bash -c "./bin/setup && ./bin/rake assets:precompile && ./bin/bundle exec rspec"
