---
name: Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Pull docker images
        run: |
          docker pull ruby:2.7.2-alpine
          docker-compose -f docker-compose.ci.yml pull
      - uses: satackey/action-docker-layer-caching@v0
        with:
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-
      - name: Cache Assets
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            public/assets
            public/packs-test
          key: ${{ runner.os }}-assets-${{ hashFiles('**/yarn.lock') }}
      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: |
            vendor/bundle
          key: ${{ runner.os }}-bundle-${{ hashFiles('**/Gemfile.lock') }}
      - name: Build Latest
        run: |
          docker-compose -f docker-compose.ci.yml build --build-arg USER_ID="$(id -u)" --build-arg GROUP_ID="$(id -u)" test
      - name: Run tests
        run: |
          docker-compose -f docker-compose.ci.yml run --rm --user="$(id -u):$(id -g)" test
      - name: Clean Up After Tests
        run: |
          docker image prune -f
          docker volume prune -f
